### ISSUE TITLE
Possible disaccord with the Uniswap docs

### ISSUE THREAD

**Issue by paulrberg** [Austin-Williams/uniswap-flash-swapper#11]
From the [README](https://github.com/Austin-Williams/uniswap-flash-swapper/tree/2066443c9d03237a6da2b645e14230c47e2e2f41#fees):

> If you are swapping a non-{ETH, WETH} token for another non-{ETH, WETH} token, then you'll be charged a 0.6% fee because your swap will touch two UniswapV2 pairs (they are routed through the WETH).

I found this odd when I read it, since the Uniswap v2 [whitepaper](https://uniswap.org/whitepaper.pdf) makes it clear that one of the goals of v2 was to move away from the WETH-as-the-central-token-router model.

In addition, the docs on [flash swap repayment](https://uniswap.org/docs/v2/smart-contract-integration/using-flash-swaps/#repayment) don't mention anything about having to pay 0.6% for non-{ETH,WETH} to non-{ETH,WETH} swaps.

My hunch is that you only pay 0.6% when there is no direct pair between token A and token B, whatever A and B might be.

**Comment by Austin-Williams** [comment]
Yes, everything you said is correct.

The current implementation in this repo is super basic, and so doesn't do any complex "routing".
When you perform a swap via Uniswap (through its router) you have to tell it what route you want to use to perform the swap. (This is hidden from the user by Uniswap's UI, but it's what happens at the contract level).

To keep this contract simple, I just enforce a basic "always trade with the X/ETH pair" route. That way I don't have to do any off-chain work to figure out what the best route is. For any non-{ETH,WETH} to non-{ETH,WETH} swaps, I just choose the route that goes through ETH -- basically mimicking the old UniswapV1 start topology.

It would be possible to refactor this contract so that it accepted custom routes instead of always trading through ETH, but for my particular use cases I don't need that functionality. So I'll just keep the "enforced swapping through ETH" property for this repo.
